services:
  db:
    image: postgres:16-alpine
    container_name: postgres_condominio
    command: ["postgres", "-c", "timezone=${APP_TIMEZONE}"]

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${APP_TIMEZONE}
      PGTZ: ${APP_TIMEZONE}
      API_SECURITY_TOKEN_SECRET: ${TOKEN}

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_condominio

    env_file:
      - .env

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      APP_TIMEZONE: ${APP_TIMEZONE}
      TZ: ${APP_TIMEZONE}
      JAVA_TOOL_OPTIONS: -Duser.timezone=${APP_TIMEZONE}
      APP_BOOTSTRAP_ADMIN_ENABLED: true
      APP_BOOTSTRAP_ADMIN_NOME: ${APP_BOOTSTRAP_ADMIN_NOME}
      APP_BOOTSTRAP_ADMIN_EMAIL: ${APP_BOOTSTRAP_ADMIN_EMAIL}
      APP_BOOTSTRAP_ADMIN_SENHA: ${APP_BOOTSTRAP_ADMIN_SENHA}
      APP_CHAMADO_ATRASO_SCHEDULER_ENABLED: true
      APP_CHAMADO_ATRASO_SCHEDULER_INITIAL_DELAY_MS: ${APP_CHAMADO_ATRASO_SCHEDULER_INITIAL_DELAY_MS}
      APP_CHAMADO_ATRASO_SCHEDULER_FIXED_DELAY_MS: ${APP_CHAMADO_ATRASO_SCHEDULER_FIXED_DELAY_MS}

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
