spring.application.name=gerenciador-chamados

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

api.security.token.secret=${TOKEN}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

app.bootstrap.admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:true}
app.bootstrap.admin.nome=${APP_BOOTSTRAP_ADMIN_NOME:Administrador}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin@condominio.local}
app.bootstrap.admin.senha=${APP_BOOTSTRAP_ADMIN_SENHA:admin123}
